export const CREATE_ORDER_DETAILS_REQUEST = 'CREATE_ORDER_DETAILS_REQUEST';
export const CREATE_ORDER_DETAILS_SUCCESS = 'CREATE_ORDER_DETAILS_SUCCESS';
export const CREATE_ORDER_DETAILS_ERROR = 'CREATE_ORDER_DETAILS_ERROR';

export const GET_ITEM_DETAILS_REQUEST = 'GET_ITEM_DETAILS_REQUEST';
export const GET_ITEM_DETAILS_SUCCESS = 'GET_ITEM_DETAILS_SUCCESS';
export const GET_ITEM_DETAILS_ERROR = 'GET_ITEM_DETAILS_ERROR';

export const GET_ORDER_DETAILS_REQUEST = 'GET_ORDER_DETAILS_REQUEST';
export const GET_ORDER_DETAILS_SUCCESS = 'GET_ORDER_DETAILS_SUCCESS';
export const GET_ORDER_DETAILS_ERROR = 'GET_ORDER_DETAILS_ERROR';
